refugio/apps/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.mascota.views import listadousuarios, index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
	MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'), 
    url(r'^nuevo$',  login_required(MascotaCreate.as_view()), name='mascota_crear'), #La clase MascotaCreate la mandamos como view usando el as_view()
 	url(r'^listar', login_required(MascotaList.as_view()), name='mascota_listar'), #La clase MascotaList la mandamos como view usando el as_view()
 	url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name="mascota_editar"),#pk significa primary key
 	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name="mascota_eliminar"),#pk significa primary key
 	url(r'^listado', listadousuarios, name="listado"),
]

refugio/refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),#Incluyo el archivo urls.py de la aplicacion mascota 
	url(r'^adopcion/', include('apps.adopciones.urls', namespace="adopciones")), #Incluyo el archivo urls.py de la aplicacion adopciones
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")), #Incluyo el archivo urls.py de la aplicacion adopciones    
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]
    

refugio/apps/mascota/models.py
from django.db import models

from apps.adopciones.models import Persona
# Create your models here.


class Vacuna(models.Model):
	nombre = models.CharField(max_length=50)

	def __str__(self): 
		return '{}'.format(self.nombre)


#Mascota extiende de Model, por eso, al igual que con todos los 
#modelos que creemos debemos colocar entre parentesis models.Model

class Mascota(models.Model): 
	#atributos o campos
	#a nombre le asignamos el tipo de dato o de campo
	#etc
	#folio = models.CharField(max_length=10, primary_key=True)
	nombre = models.CharField(max_length=50)
	sexo = models.CharField(max_length=10)
	edad_aproximada = models.IntegerField()
	fecha_rescate = models.DateField()
	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE) #Llave Foranea
	vacuna = models.ManyToManyField(Vacuna, blank=True) #Muchos a Muchos

refugio/apps/mascota/forms.py
from django import forms

#importo el modelo Mascota
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

	class Meta:
		#De que modelo crearemos este formulario
		model = Mascota

		#Definiremos los campos del modelo
		fields = [
			'nombre',
			'sexo',
			'edad_aproximada',
			'fecha_rescate',
			'persona',
			'vacuna',
		]

		#Ahora asignamos las etiquetas que van a tener a la hora
		#de pintar el formulario

		labels = {
			#Aqui escribimos el diccionario
			'nombre': 'Nombre',
			'sexo': 'Sexo',
			'edad_aproximada': 'Edad Aproximada',
			'fecha_rescate': 'Fecha de Rescate',
			'persona': 'Adoptante',
			'vacuna': 'Vacuna',
		}

		#Aqui declaramos los widgets
		#Los widgets son los que se van a pintar a forma 
		#de etiquetas html

		widgets = {
			#A los widgets se les puede colocar los atributos de la clase, form-control es el que viene con bootstrap
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'sexo': forms.TextInput(attrs={'class':'form-control'}),
			'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
			#Este atributo es una llave foranea, asi que conviene que sea un Select
			'persona': forms.Select(attrs={'class':'form-control'}),
			#Este campo vacuna es un campo many to many, entonces usaremos el CheckboxSelectMultiple que nos entrega Django
			'vacuna': forms.CheckboxSelectMultiple(),
		}
		

refugio/apps/mascota/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User#Importamos el modelo User para probar la serializacion de objetos
#Esto lo importe
from django.http import HttpResponse

#Importar los serializers
from django.core import serializers

#Agrego el urlresolver reverse_lazy
from django.core.urlresolvers import reverse_lazy

#Agregamos el view ListView de django
from django.views.generic import ListView, CreateView, UpdateView,DeleteView

#Importamos el formulario MascotaForm
from apps.mascota.forms import MascotaForm

#Importamos el modelo Mascota de apps/mascota/models.py
from apps.mascota.models import Mascota



def listadousuarios(request):
	lista = serializers.serialize('json', User.objects.all(), fields=['username','first_name'])#esta variable nos serializara los objetos
#El queryset Mascota.objects.all() traerá todos los objetos de Modelo Mascota.
	return HttpResponse(lista, content_type='application/json')#devuelve la lista


# Create your views here.
def index(request):
	return render(request, 'mascota/index.html') # render es un shortcut que recibe dos parametros: el request y el nombre de la plantilla

#vista basada en funcion, antes era solo vista basada en funcion
#pero despues veremos las vistas basadas en clase que es algo más
#nuevo para Django
def mascota_view(request):
#Si el metodo que recibe la peticion (osease request) es un POST, entonces se van a recibir
#los datos que se están mandando en el POST de nuestro formulario
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		#Si lo que se recibe es un POST, preguntaremos si los datos son validos
		if form.is_valid():
			#si los datos son validos se guardaran los datos en el formulario
			form.save()
		#Despues de guardar los datos somos redirigidos a una url
		#Esa url será el index de mascota
		return redirect('mascota:mascota_listar')
		#Si no es un metodo POST le vamos a decir que nos vuelva a renderizar el formulario.
	else:
		#Esto lo usaremos cuando el metodo de envio sea un GET
		form = MascotaForm()

		#Por ultimo le mandariamos la respuesta que llevaría un request, el nombre del template
		#y el contexto, que en este caso es el formulario form mandado en un diccionario
		return render(request, 'mascota/mascota_form.html', {'form':form})

		#En el contexto la clave es form y va a contener el form que es el de 
		# la linea 19, es decir, form = MascotaForm(request.POST)


def mascota_list(request):
			#definimos nuestro queryset, al que le diremos que nos traiga todos los
			#objetos que están en nuestro modelo mascota.
			mascota = Mascota.objects.all().order_by('id')
			#A la variable contexto se le asigna el diccionario mascotas 
			#La clave de diccionario va a ser mascotas y va a ser igual a todo
			#lo que obtuvo en nuestro query set, osease Mascota.objects.all()
			contexto = {'mascotas':mascota}
			#retornamos un render, aqui mandamos el template, el nombre del template
			#y el contexto
			return render(request, 'mascota/mascota_list.html', contexto)


#Esta VISTA o funcion recibira un request y el id de mascota
def mascota_edit(request, id_mascota):		
	#Primero vamos a crear un Queryset el cual va a tener un objeto 
	#al que corresponde al id que estamos enviando
	mascota = Mascota.objects.get(id=id_mascota)
	#ahora mandamos los datos de este objeto a nuestro formulario.
	#Si el metodo es un GET lo que va a hacer es que nuestro formulario, 
	#lo va a rellenar con una instancia de el objeto que recogimos anteriormente.
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	#Despues de recoger el POST del Formulario, lo instanciara
	#al objeto para guardar los cambios del objeto recogido 
	#de acuerdo a los parametros que estamos mandando.
	else:
		form = MascotaForm(request.POST, instance=mascota)
		#Aqui evaluamos si el formulario es valido
		if form.is_valid():
			#Y si es valido, guardará los cambios
			form.save()	
			#Después de realizar esto nos redirigirá a otra url
			#que podría ser por ejemplo el listado de mascotas
			return redirect('mascota:mascota_listar')
	#Luego retornamos el render y le ponemos el template que
	#usamos para guardar y como contexto le enviamos el formulario
	return render(request, 'mascota/mascota_form.html', {'form':form})


#Vista para eliminar registro de modelo Mascota
def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':#Si el metodo es POST vamos a borrar el objeto
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})
	#Y retornamos el render, y lo mandaremos a un template
	#llamado mascota_delete y como contexto le mandamos
	#el objeto de la mascota


#Vistas basadas en clase.

#Creamos clase MascotaList que extiende de vista generica ListView
class MascotaList(ListView):
	#Le indicamos el modelo y le indicamos a que template enviaremos este contexto
	model = Mascota#.objects.all().order_by('id')
	template_name = 'mascota/mascota_list.html'
	paginate_by = 2 #cuantos objetos mandamos por pagina, en este caso solo muestra dos elementos por pagina

#Creamos clase MascotaCreate que extiende de vista generica CreateView
class MascotaCreate(CreateView):
	model = Mascota#modelo Mascota
	form_class = MascotaForm#formulario es MascotaForm
	template_name = 'mascota/mascota_form.html'#el template html
	#Una vez que guardemos nuestros registos, redirigimos a mascota_list
	success_url = reverse_lazy('mascota:mascota_listar')


	#Vista de clase Update
class MascotaUpdate(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

	#Vista de clase Delete
class MascotaDelete(DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')

refugio/templates/mascota/index.html
{% extends 'base/base.html' %}

{% block title %} Mascota {% endblock %}
{% block content %} <h1> Soy el contenido de la app mascota </h1> {% endblock %}

refugio/templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="POST">
	<!--EL TOKEN CSRF DEBE INCLUIRSE EN TODOS LOS FORMULARIOS, PARA QUE NO NOS MARQUE UN ERROR -->
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombre }} ?</h3>
	<button class="btn btn-danger" type="submit">Si, Eliminar</button>
	<!--url para cancelar y que nos lleve nuevamente al listado de las mascotas-->
	<a class = "btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
</form>

{% endblock %}

refugio/templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method="POST">
	<!--EL TOKEN CSRF DEBE INCLUIRSE EN TODOS LOS FORMULARIOS, PARA QUE NO NOS MARQUE UN ERROR -->
	{% csrf_token %}
	<!--Meteremos en una variable el form que estamos recibiendo en el contexto-->
	{{form.as_p}} <!--al hacer form.as_p le estamos indicando que lo pinte como parrafo, como si fuera una etiqueta <p></p>-->
	<!--Finalmente generamos el boton de submit para enviar los datos-->
	<button type="submit">Guardar</button>
</form>

{% endblock %}

refugio/templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Sexo</td>
			<td>Edad</td>
			<td>Fecha de Rescate</td>
			<td>Vacunas</td>
			<td>Adoptante</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for mascota in object_list %}
		<tr>
			<td>{{ mascota.id }}</td>
			<td>{{ mascota.nombre }}</td>
			<td>{{ mascota.sexo }}</td>
			<td>{{ mascota.edad_aproximada }}</td>
			<td>{{ mascota.fecha_rescate }}</td>
			<td>
			<ul>{% for vacuna in mascota.vacuna.all %}
				<li>
					{{vacuna.nombre}}
				</li>
				{% endfor %}
			</ul>
    		</td>
			<td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de mascotas</h1>
		{% endif %}
	</tbody>
</table> 
<!--Paginacion-->
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul>
<!--Termina Paginacion-->
{% endblock%}